/*
 * File: FEMhub.ModuleBasicAdaptWindow.ui.js
 * Date: Fri Dec 17 2010 21:14:37 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('FEMhub');
FEMhub.ModuleBasicAdaptWindowUi = Ext.extend(Ext.Window, {
    title: 'Module Basic Adapt',
    width: 930,
    height: 610,
    layout: 'fit',
    boxMinHeight: 610,
    boxMinWidth: 930,
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                title: '',
                ref: 'main_tabs',
                id: 'main_tabs',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Geometry',
                        layout: 'fit',
                        tpl: '',
                        html: '',
                        ref: '../geometry_tab',
                        id: 'geometry_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Operate on Nodes',
                                    ref: '../../../nodes_button'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Edges'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Subdomains'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Model',
                        layout: 'border',
                        ref: '../model_tab',
                        id: 'model_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Boundary Conditions',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Add new...',
                                                menu: {
                                                    xtype: 'menu',
                                                    items: [
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Dirichlet'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Neumann'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Newton'
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'List:'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Materials',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Add new...'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'List:'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                region: 'center',
                                autoScroll: true
                            },
                            {
                                xtype: 'panel',
                                region: 'west',
                                width: 142,
                                autoScroll: true,
                                split: true,
                                ref: '../../model_parameters'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Computation',
                        width: 770,
                        layout: 'border',
                        ref: '../computation_tab',
                        id: 'computation_tab',
                        items: [
                            {
                                xtype: 'panel',
                                title: '',
                                autoScroll: true,
                                layout: 'absolute',
                                padding: 10,
                                shadow: 'frame',
                                width: 235,
                                height: 544,
                                itemId: 'computation_setup',
                                region: 'west',
                                ref: '../../computation_setup',
                                id: 'computation_setup',
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: 'Mesh refinements:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 12
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Threshold:',
                                        height: 20,
                                        width: 60,
                                        x: 10,
                                        y: 332
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Strategy:',
                                        height: 20,
                                        width: 80,
                                        x: 120,
                                        y: 332
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 0,
                                        x: 110,
                                        y: 10,
                                        width: 50,
                                        height: 20,
                                        maxValue: 10,
                                        minValue: 0,
                                        decimalPrecision: 0,
                                        allowNegative: false,
                                        allowDecimals: false,
                                        ref: '../../../Init_ref_num',
                                        id: 'Init_ref_num'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: '0.3',
                                        x: 70,
                                        y: 330,
                                        width: 40,
                                        height: 20,
                                        maxValue: 1,
                                        minValue: 0,
                                        allowNegative: false,
                                        ref: '../../../Adapt_threshold',
                                        id: 'Adapt_threshold'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 2,
                                        x: 70,
                                        y: 390,
                                        width: 50,
                                        height: 20,
                                        maxValue: 1000,
                                        minValue: 0,
                                        allowNegative: false,
                                        decimalPrecision: 8,
                                        ref: '../../../Err_weight_1',
                                        id: 'Err_weight_1'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 1,
                                        x: 120,
                                        y: 390,
                                        width: 50,
                                        height: 20,
                                        maxValue: 1000,
                                        minValue: 0,
                                        allowNegative: false,
                                        decimalPrecision: 8,
                                        ref: '../../../Err_weight_2',
                                        id: 'Err_weight_2'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: '1.4142',
                                        x: 170,
                                        y: 390,
                                        width: 50,
                                        height: 20,
                                        maxValue: 1000,
                                        minValue: 0,
                                        allowNegative: false,
                                        decimalPrecision: 4,
                                        ref: '../../../Err_weight_3',
                                        id: 'Err_weight_3'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 1,
                                        x: 180,
                                        y: 330,
                                        width: 40,
                                        height: 20,
                                        maxValue: 2,
                                        minValue: 0,
                                        decimalPrecision: 0,
                                        allowDecimals: false,
                                        allowNegative: false,
                                        ref: '../../../Adapt_strategy',
                                        id: 'Adapt_strategy'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: -1,
                                        x: 70,
                                        y: 360,
                                        width: 40,
                                        height: 20,
                                        maxValue: 5,
                                        minValue: -1,
                                        decimalPrecision: 0,
                                        allowDecimals: false,
                                        ref: '../../../Mesh_regularity',
                                        id: 'Mesh_regularity'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 1,
                                        x: 180,
                                        y: 360,
                                        width: 40,
                                        height: 20,
                                        maxValue: 5,
                                        minValue: 0,
                                        allowNegative: false,
                                        ref: '../../../Conv_exp',
                                        id: 'Conv_exp'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Polynomial degree:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 32
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 4,
                                        x: 110,
                                        y: 30,
                                        width: 50,
                                        height: 20,
                                        maxValue: 9,
                                        minValue: 1,
                                        decimalPrecision: 0,
                                        allowDecimals: false,
                                        allowNegative: false,
                                        ref: '../../../Init_p',
                                        id: 'Init_p'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Max relative error:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 52
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: '0.1',
                                        x: 110,
                                        y: 50,
                                        width: 50,
                                        height: 20,
                                        decimalPrecision: 6,
                                        allowNegative: false,
                                        ref: '../../../Err_stop',
                                        id: 'Err_stop'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Max number steps:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 72
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 10,
                                        x: 110,
                                        y: 70,
                                        width: 50,
                                        height: 20,
                                        allowDecimals: false,
                                        allowNegative: false,
                                        minValue: 1,
                                        maxValue: 1000,
                                        ref: '../../../Max_num_steps',
                                        id: 'Max_num_steps'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Max number DOF:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 92
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Mesh reg:',
                                        height: 20,
                                        width: 60,
                                        x: 10,
                                        y: 362
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Exponent:',
                                        height: 20,
                                        width: 60,
                                        x: 120,
                                        y: 362
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Weights:',
                                        height: 20,
                                        width: 60,
                                        x: 10,
                                        y: 392
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 50000,
                                        x: 110,
                                        y: 90,
                                        width: 50,
                                        height: 20,
                                        maxValue: 999999,
                                        minValue: 1,
                                        allowDecimals: false,
                                        allowNegative: false,
                                        ref: '../../../Ndof_stop',
                                        id: 'Ndof_stop'
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: 'Matrix solver',
                                        height: 200,
                                        width: 100,
                                        layout: 'auto',
                                        itemId: 'ms_field_set',
                                        x: 10,
                                        y: 120,
                                        ref: '../../../ms_field_set',
                                        id: 'ms_field_set',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'Amesos',
                                                inputValue: 'amesos',
                                                value: 'amesos',
                                                name: 'ms_radio_group',
                                                itemId: 'ms_radio_1',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_1'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'AztecOO',
                                                name: 'ms_radio_group',
                                                value: 'aztecoo',
                                                itemId: 'ms_radio_2',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_2'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'MUMPS',
                                                name: 'ms_radio_group',
                                                value: 'mumps',
                                                itemId: 'ms_radio_3',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_3'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'Pardiso',
                                                name: 'ms_radio_group',
                                                value: 'pardiso',
                                                itemId: 'ms_radio_4',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_4'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'PETSc',
                                                name: 'ms_radio_group',
                                                value: 'petsc',
                                                itemId: 'ms_radio_5',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_5'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'SuperLU',
                                                name: 'ms_radio_group',
                                                value: 'superlu',
                                                itemId: 'ms_radio_6',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_6'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'UMFpack',
                                                checked: true,
                                                name: 'ms_radio_group',
                                                value: 'umfpack',
                                                itemId: 'ms_radio_7',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_7'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: 'Adaptivity',
                                        height: 200,
                                        width: 100,
                                        layout: 'auto',
                                        itemId: 'adapt_field_set',
                                        x: 120,
                                        y: 120,
                                        ref: '../../../adapt_field_set',
                                        id: 'adapt_field_set',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'hp aniso',
                                                inputValue: 'hp_aniso',
                                                value: 'hp_aniso',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_1',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_1'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'hp aniso h',
                                                inputValue: 'hp_aniso_h',
                                                value: 'hp_aniso_h',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_2',
                                                checked: true,
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_2'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'hp aniso p',
                                                inputValue: 'hp_aniso_p',
                                                value: 'hp_aniso_p',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_3',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_3'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'hp iso',
                                                inputValue: 'hp_iso',
                                                value: 'hp_iso',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_4',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_4'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'h aniso',
                                                inputValue: 'h_aniso',
                                                value: 'h_aniso',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_5',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_5'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'h iso',
                                                inputValue: 'h_iso',
                                                value: 'h_iso',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_6',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_6'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'p aniso',
                                                inputValue: 'p_aniso',
                                                value: 'p_aniso',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_7',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_7'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'p iso',
                                                inputValue: 'p_iso',
                                                value: 'p_iso',
                                                name: 'adapt_radio_group',
                                                itemId: 'adapt_radio_8',
                                                ref: '../../../../Adapt_type',
                                                id: 'adapt_radio_8'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Run',
                                        iconCls: '',
                                        cls: '',
                                        height: 20,
                                        iconAlign: 'bottom',
                                        x: 170,
                                        y: 440,
                                        width: 50,
                                        itemId: 'computation_adapt',
                                        ref: '../../../computation_adapt',
                                        id: 'computation_adapt'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                region: 'center',
                                width: 100,
                                layout: 'border',
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: '',
                                        layout: 'absolute',
                                        height: 390,
                                        width: 100,
                                        itemId: 'computation_result',
                                        autoScroll: true,
                                        padding: 10,
                                        region: 'center',
                                        ref: '../../../computation_result',
                                        id: 'computation_result'
                                    },
                                    {
                                        xtype: 'panel',
                                        title: '',
                                        height: 110,
                                        layout: 'absolute',
                                        width: 100,
                                        shim: false,
                                        itemId: 'computation_log',
                                        autoScroll: true,
                                        padding: 10,
                                        region: 'south',
                                        ref: '../../../computation_log',
                                        id: 'computation_log'
                                    }
                                ]
                            }
                        ],
                        bbar: {
                            xtype: 'toolbar',
                            height: 25,
                            buttonAlign: 'center',
                            id: 'status_bar'
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Postprocessing',
                        layout: 'fit',
                        ref: '../postprocessing_tab',
                        id: 'postprocessing_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Point Values'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Line Integrals'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Volume Integrals'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                title: '',
                                layout: 'fit',
                                autoScroll: true,
                                ref: '../../postprocessing_panel'
                            }
                        ]
                    }
                ]
            }
        ];
        FEMhub.ModuleBasicAdaptWindowUi.superclass.initComponent.call(this);
    }
});
